yonitou/cosmose

app/javascript/packs/application.js
app/javascript/packs/components/init_select2.js
app/javascript/packs/components/inputs_empty_registration.js
app/views/devise/registrations/new.html.erb

Registration in 2 steps with JS

Registration in 2 steps

---

app/models/block.rb
app/models/user.rb
db/migrate/20200611133055_create_blocks.rb
db/migrate/20200611133829_add_default_value_to_private_column.rb
db/schema.rb
test/models/block_test.rb

- created block model
- added validation on content & user_id
- added default value to private : false

Block model

---

app/controllers/notifications_controller.rb
app/controllers/user_likes_controller.rb
app/models/notification.rb
app/models/project.rb
app/models/user.rb
app/views/notifications/index.html.erb
config/routes.rb
db/migrate/20200611134755_create_notifications.rb
db/migrate/20200611143622_rename_type_column_name_to_group.rb
db/schema.rb
test/controllers/notifications_controller_test.rb
test/models/notification_test.rb

model notification, controller notification, like notifications done

Notifications

---

app/assets/stylesheets/components/_footer.scss
app/controllers/blocks_controller.rb
app/controllers/projects_controller.rb
app/models/block.rb
app/views/projects/show.html.erb
config/routes.rb
db/migrate/20200611144740_create_active_storage_tables.active_storage.rb
db/schema.rb
test/controllers/blocks_controller_test.rb

- created block controller
- added private method block_params
- edited project#show to display blocks
- splitted public & private blocks on project#show
- added image upload & display (installed active record)

Block controller

---

app/assets/stylesheets/pages/_home.scss
app/javascript/packs/application.js
app/javascript/packs/components/type.js
app/views/shared/_homepage-visitor.html.erb

animation homepage visitor banner type

---

app/assets/stylesheets/pages/_explorer.scss
app/assets/stylesheets/pages/_index.scss
app/views/pages/explorer.html.erb

added effect button search

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_explorer.scss
app/views/pages/explorer.html.erb
app/views/shared/_card-artist.html.erb
app/views/shared/_card-project.html.erb
app/views/shared/_homepage-user.html.erb
app/views/shared/_navbar.html.erb

c'est plus des corrections de petites mer douilles que du design explorer mais bon

Explorer design continued

---

app/controllers/collaborations_controller.rb
app/controllers/projects_controller.rb
app/controllers/user_likes_controller.rb
app/models/collaboration.rb
app/models/project.rb
app/models/user.rb
app/views/collaborations/_new.html.erb
app/views/projects/show.html.erb
config/routes.rb
db/migrate/20200611194758_remove_columns_from_notifications.rb
db/migrate/20200611195218_drop_notification_rooms.rb
db/migrate/20200611195551_remove_notificationroom_from_notification.rb
db/migrate/20200611195812_add_column_to_collaborations.rb
db/migrate/20200611200539_drop_collaborations.rb
db/migrate/20200611200901_create_collaborations.rb
db/schema.rb
test/controllers/collaborations_controller_test.rb
test/models/collaboration_test.rb

- Collaborations controller 
- Notifications sent when request created
- Accept & decline on show page 
- Collaborations model

Change notifications mode

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_portfolio.scss
app/javascript/packs/components/profile_user_display.js
app/views/pages/portfolio.html.erb

design v1 profile done

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_project-new.scss
app/javascript/packs/application.js
app/javascript/packs/components/inputs_empty_project_new.js
app/views/devise/registrations/new.html.erb
app/views/projects/new.html.erb

Form new project

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_project-show.scss
app/views/layouts/application.html.erb
app/views/shared/_homepage-visitor.html.erb
db/seeds.rb

- created seeds file with users & projects
- edited seeds users email & password to be easily accessible => email1..5@cosmose.art / azerty
- fixed gradient on collab button on project#show 
- added gradient design on secondary button, primary button font-size++
- improved titles on homepage
- fixed homepage button & footer

Small design fixes

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/collaborations_controller.rb
app/controllers/notifications_controller.rb
app/controllers/projects_controller.rb
app/controllers/user_likes_controller.rb
app/policies/application_policy.rb
app/policies/collaboration_policy.rb
app/policies/project_policy.rb
app/policies/user_like_policy.rb
app/views/notifications/index.html.erb
app/views/projects/show.html.erb
app/views/shared/_homepage-user.html.erb
app/views/shared/_navbar.html.erb
test/policies/collaboration_policy_test.rb
test/policies/project_policy_test.rb
test/policies/user_like_policy_test.rb

Pundit done :D :D :D :D :D (bug to fix on notifications controller)

---

app/assets/stylesheets/components/_card.scss
app/views/pages/explorer.html.erb
app/views/shared/_card-artist.html.erb
app/views/shared/_card-project.html.erb

Corrected HTML for cards artists & projects --> RESOLVED

fixed bug cards

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_portfolio.scss
app/views/pages/explorer.html.erb
app/views/pages/portfolio.html.erb

Artist page project part

---

app/assets/stylesheets/components/_animation_page_portfolio.scss
app/assets/stylesheets/pages/_portfolio.scss
app/javascript/packs/application.js
app/javascript/packs/components/portoflio_toggle.js
app/views/pages/portfolio.html.erb

- coded portfolio toggle
- added style on toggle

Portfoio toggle

---

app/javascript/packs/components/init_select2.js
app/models/user.rb
app/views/devise/registrations/new.html.erb

Maximum 3 selections for project categories 
Need to select at least one skill at registration

Select 2 minor fixe + registration fixed 

---

app/assets/stylesheets/components/_icons.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_notification.scss
app/controllers/collaborations_controller.rb
app/controllers/user_likes_controller.rb
app/views/notifications/index.html.erb

design notification page

---

app/views/layouts/application.html.erb
app/views/shared/_alerts.html.erb

- Created alerts partial
- Rendered from application layout

alerts done

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_project-show.scss
app/javascript/packs/application.js
app/javascript/packs/components/collaborer_form.js
app/views/projects/show.html.erb

Amélioration de la show visiteur
Passage des labels en paragraphe
Message apparait que après click sur collaborer

show visiteurs

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_icons.scss
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb

Footer v1 to improve + animation on scroll

Footer v1 to improve

---

app/assets/stylesheets/pages/_project-show.scss
app/views/projects/show.html.erb

fix bug show

---

app/controllers/application_controller.rb
app/controllers/users_controller.rb
app/javascript/packs/components/portoflio_toggle.js
app/views/projects/show.html.erb
app/views/shared/_card-artist.html.erb
app/views/shared/_homepage-user.html.erb
app/views/users/show.html.erb
config/routes.rb
test/controllers/users_controller_test.rb

Artists show
All cards mapped
Toggle JS improvement for portfolio
user show + users controller

Artists show, JS improvements & links mapped

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_icons.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_project-show.scss
app/views/projects/show.html.erb

A améliorer après correction des bugs: 
- bouton modifier qui marche pas
- bouton supprimer changer la redirection
- faire en sorte de pouvoir supprimer les request quand le status est plus pending
- faire apparaitre les collaborateurs actuels
- limiter au traitement d’une request à la fois ? 
- faire en sorte que lorsqu’on a envoyé une demande le carré blanc prenne la place du bouton collaborer

front de la page projet

---

app/assets/stylesheets/components/_animation_page_portfolio.scss
app/views/pages/explorer.html.erb
app/views/pages/portfolio.html.erb
app/views/users/show.html.erb
touch.env

Fixing buttons

---

Gemfile
app/assets/stylesheets/components/_card.scss
app/javascript/packs/components/block_form.js
app/javascript/packs/components/project_toggle.js
app/javascript/plugins/init_autocomplete.js
app/views/pages/portfolio.html.erb
app/views/projects/show.html.erb
app/views/shared/_card-artist.html.erb
app/views/shared/_homepage-user.html.erb
app/views/users/show.html.erb

JS fixes + avatars linked + portfolio path if show user == current_uer + algolia autocomplete on search address

JS fixes + avatars linked + portfolio path + Algolia

---

app/assets/stylesheets/components/_animation_page_portfolio.scss
app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_portfolio.scss
app/assets/stylesheets/pages/_project-new.scss
app/views/pages/explorer.html.erb
app/views/pages/portfolio.html.erb
app/views/projects/show.html.erb
app/views/shared/_homepage-user.html.erb
app/views/shared/_navbar.html.erb

SECONDARY
SECONDARY HOVER
PRIMARY
PRIMARY HOVER

fixed btns

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_portfolio.scss
app/controllers/blocks_controller.rb
app/views/shared/_navbar.html.erb
app/views/users/show.html.erb

- Added logo on both navbars
- Fixed skill design on portfolio
- Replicated portfolio on user#show

Logo & portfolio

---

app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/pages/about.html.erb
config/locales/simple_form.en.yml

All the translation done for the pages of the demo (not the mailers)
Just missing a way to change the language on "Choose a photo" / "No file chosen"

Translation form

---

Gemfile
Gemfile.lock
app/assets/stylesheets/pages/_explorer.scss
app/controllers/pages_controller.rb
app/javascript/packs/application.js
app/javascript/packs/components/init_search_select2.js
app/javascript/plugins/init_autocomplete.js
app/models/project.rb
app/views/pages/explorer.html.erb

search avec select2 sans front

Search select2

---

app/assets/stylesheets/components/_homepage-user.scss
app/views/shared/_homepage-user.html.erb

effects on categories in homepage + reviewed design

---

app/assets/stylesheets/pages/_notification.scss
app/controllers/collaborations_controller.rb
app/controllers/user_likes_controller.rb
app/views/notifications/index.html.erb
app/views/shared/_project_block_form.html.erb
db/seeds.rb

uniformisation des notifs,
replaced icons by solids icons,
added smooth hover effect

Notifications front

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_icons.scss
app/views/shared/_admin-icons.html.erb
app/views/shared/_card-artist.html.erb
app/views/shared/_card-project.html.erb
app/views/shared/_homepage-user.html.erb
app/views/shared/_icons.html.erb

iF / ELSIF on project categories to make them appear in cards 
Only 1 icon per card
Method in the render 'shared/icons'
Created a file icons-admin for icons used outside of categories
Deleted the icons from users' cards 
Fixed design

Fixing icons

---

app/assets/stylesheets/components/_icons.scss
app/assets/stylesheets/pages/_project-show.scss
app/views/projects/show.html.erb

Show front

---

app/assets/stylesheets/components/_navbar.scss
app/controllers/user_likes_controller.rb
app/views/notifications/index.html.erb
app/views/shared/_navbar.html.erb

Notifications sorted, notifications date (french format & timezone), notifications numbers count in navbar

Notifications v3

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_explorer.scss
app/javascript/packs/components/init_search_select2.js
app/views/pages/explorer.html.erb

Choix a faire sur le display de la recherche par category/competences

amelioration front explorer

---

app/assets/stylesheets/pages/_project-new.scss
app/views/projects/new.html.erb
app/views/shared/_card-artist.html.erb

new project category design

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_icons.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_explorer.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_inbox.scss
app/assets/stylesheets/pages/_project-new.scss
app/controllers/chatrooms_controller.rb
app/javascript/packs/application.js
app/javascript/packs/components/active_category_project.js
app/javascript/packs/components/block_form.js
app/javascript/packs/components/chatroom_form.js
app/models/chatroom.rb
app/views/chatrooms/index.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_homepage-user.html.erb

- inbox improvements (focus on form to be fixed)
- new project category toggle
- fixed homepage débordement ?
- small changes on cards
- fix notification badge

Inbox redesign

---

app/controllers/blocks_controller.rb
db/seeds.rb

better seeds working

---

app/assets/stylesheets/pages/_explorer.scss
app/javascript/packs/components/explorer_toggle.js
app/javascript/packs/components/init_search_select2.js

search final

---

app/assets/stylesheets/components/_animation_page_portfolio.scss
app/assets/stylesheets/components/_block_display.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_explorer.scss
app/assets/stylesheets/pages/_inbox.scss
app/assets/stylesheets/pages/_project-show.scss
app/views/chatrooms/index.html.erb
app/views/messages/_message.html.erb
app/views/projects/show.html.erb
app/views/shared/_block_display.html.erb

- added link on collab request
- added link on existing collab
- fix links & collabs number
- fix excessive padding on portfolio/show
- fix excessive padding on project show &
- replaced bin by cross on block & better hover
- added project links to inbox

Quick fixes

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_block_display.scss
app/assets/stylesheets/components/_block_form.scss
app/assets/stylesheets/pages/_inbox.scss
app/controllers/blocks_controller.rb
app/views/messages/_message.html.erb
app/views/messages/_message_broadcasted.html.erb
app/views/pages/portfolio.html.erb
app/views/shared/_artist_block_form.html.erb
app/views/shared/_block_display.html.erb
app/views/shared/_project_block_form.html.erb

- changed blocks form (translation & block -> contenu)
- fix width of youtube video
- side by side blocks
- improved audio block
- add avatar to messages in inbox

Block fixes

---

app/assets/stylesheets/pages/_inbox.scss
app/controllers/users_controller.rb
app/models/user.rb
app/views/chatrooms/index.html.erb

- fixed header on inbox
- corrected width of messages

Fix inbox v3

---

app/assets/stylesheets/pages/_inbox.scss
app/views/chatrooms/index.html.erb
app/views/messages/_message.html.erb
app/views/messages/_message_broadcasted.html.erb

giphy en soumsoum
